/*  JOHN LOEFFLER
 *  CISC 3150
 *  SUMMER II 2017
 *
 *      POKERHANDCOMPARATOR::SUIT
 */
#ifndef SUIT_H
#define SUIT_H

/**
 *   ENUM REPRESENTING THE FOUR STANDARD PLAYING CARD SUITS
 */
enum Suit{
    CLUBS, DIAMONDS, HEARTS, SPADES
};

#endif // SUIT_H
