/*  JOHN LOEFFLER
 *  CISC 3150
 *  SUMMER II 2017
 *
 *      POKERHANDCOMPARATOR::VALUE
 */

#ifndef VALUE_H
#define VALUE_H

/**
 *   ENUM REPRESENTING THE STANDARD FACE VALUES OF A PLAYING CARD
 */
enum Value{
    TWO, THREE, FOUR, FIVE, SIX,
    SEVEN, EIGHT, NINE, TEN,
    JACK, QUEEN, KING, ACE
};
#endif // VALUE_H
